from . import hr_contract
from . import hr_contract_advantage_template
from . import hr_contribution_register
from . import hr_employee
from . import hr_leave_type
from . import hr_payroll_structure
from . import hr_payslip
from . import hr_payslip_input
from . import hr_salary_rule
from . import hr_payslip_line
from . import hr_payslip_run
from . import hr_payslip_worked_days
from . import hr_rule_input
from . import hr_salary_rule_category
from . import res_config_settings
from . import resource_mixin
from . import inherit_data
from . import human_resource
from . import master
from . import insurance_details
from . import monthly_employee_detail
from . import utilities