{
    "name": "HR Payroll",
    "version": "17.0.1.0.0",
    "category": "Human Resources",
    "summary": "Odoo 17 HR Payroll, payroll, Odoo17 Payroll, Odoo Payroll, Payroll, Odoo17 Payslips, Employee Payroll, HR Payroll,Odoo17, Odoo17 HR, odoo hr,odoo17, Accounting,Odoo Apps",
    "description": "odoo17, Odoo 17 HR Payroll, odoo payroll, odoo17 payroll, payroll community,odoo 17, payroll,Odoo 17 Payroll for Community version where can manage "
    "Employee Payroll Records",
    "author": "Shangrila Informatics",
    "depends": [
        "hr_contract",
        "hr_holidays",
        "account_fiscal_year",
        "account_move_fiscal_year",
    ],
    "sequence": 4,
    "data": [
        "security/hr_payroll_security.xml",
        "security/ir.model.access.csv",
        "data/hr_payroll_sequence.xml",
        "data/hr_payroll_data.xml",
        "data/month_data.xml",
        "data/allowance_master_data.xml",
        "wizard/hr_payslips_employees_views.xml",
        "wizard/payslip_lines_contribution_register_views.xml",
        "report/hr_payroll_report.xml",
        "report/report_contribution_register_templates.xml",
        "report/report_payslip_templates.xml",
        "report/report_payslip_details_templates.xml",
        "report/report_payroll.xml",
        "report/annual_salary_report.xml",
        "report/annual_quarter_report.xml",
        "report/report_by_head_of_expense.xml",
        "report/janpratinidhi_annual_expense.xml",
        "report/payroll_reports/advance_tds_tax.xml",
        "report/payroll_reports/bank_submit_report.xml",
        "report/payroll_reports/employee_deduction_detail.xml",
        "report/payroll_reports/employee_fund_english.xml",
        "report/payroll_reports/employee_paraisramikKatiAbhilekh.xml",
        "report/payroll_reports/hit_kosa_katti_amount.xml",
        "report/payroll_reports/kalaya_kosa_katti_amount.xml",
        "report/payroll_reports/nikasa_report.xml",
        "report/payroll_reports/sabadik_bima.xml",
        "report/payroll_reports/employee_nagarik_lagani_kosh.xml",
        "report/payroll_reports/monthly_employee_wise.xml",
        "report/payroll_reports/report_retirement.xml",
        "report/payroll_reports/employee_sapati_katti.xml",
        "report/payroll_reports/employee_kosh_katti.xml",
        "report/payroll_reports/employee_payroll_detail.xml",
        "report/payroll_reports/payroll_detail_education.xml",
        "report/payroll_reports/payroll_detail_newsalarysheet.xml",
        "report/payroll_reports/tax_calculation.xml",
        "views/hr_leave_type_views.xml",
        "views/hr_contract_views.xml",
        "views/hr_salary_rule_views.xml",
        "views/hr_salary_rule_category_views.xml",
        "views/hr_contribution_register_views.xml",
        "views/hr_payroll_structure_views.xml",
        "views/hr_payslip_views.xml",
        "views/hr_payslip_line_views.xml",
        "views/master.xml",
        "views/inherit.xml",
        "views/hr_employee_views.xml",
        "views/hr_payslip_run_views.xml",
        "views/res_config_settings_views.xml",
        "views/human_resource_views.xml",
        "views/insurance_details.xml",
        "views/monthly_employee_detail.xml",
    ],
    "demo": ["data/hr_payroll_demo.xml"],
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True,
}
