
from . import account_account
from . import account_asset
from . import account_followup
from . import account_journal
from . import account_move
from . import credit_limit
from . import product_template
from . import res_config_settings
from . import res_partner
from . import multiple_invoice
from . import multiple_invoice_layout
from . import recurring_payments
from . import account_payment
from . import res_company
from . import custom_payment
from . import location_model
from . import master
from . import website
from . import company_category_inherit
from . import res_company_inherit
from . import sale_order_inherit
# from . import load_coa
from . import service_payment
from . import inherit_date
from . import stock_picking_form_inherit
from . import translation
from . import res_user_inherit
from . import account_payment_inherit
from . import sale_order
from . import product_custom_price
from . import product_request
from . import purchase_sale_flow
from . import notification

from .ecommerce import custom_product_attr
from .ecommerce import product_arrt_values
from .ecommerce import product_arrt_templ_values
from .ecommerce import product_attr_exclusion
from .ecommerce import product_attrubutes_line
from .ecommerce import cart
from .ecommerce import wishlist
from .ecommerce import address
from .ecommerce import checkout
from .ecommerce import payments
from .ecommerce import orders
from .ecommerce import model
from .ecommerce import utils
from .ecommerce import api_access
from .ecommerce import user_activity
from .ecommerce import product_recommendations