{
    "name": "Vehicle Management",
    "author": "Robin Gurung and Asim Ghimire",
    "version": "17.0",
    "category": "",
    "application": True,
    'depends': ['base','base_accounting_kit'],
    'data': [
        'security/vehicle_security.xml',
        'security/ir.model.access.csv',
        'views/views.xml',
        'views/templates.xml',
        'views/menuitem.xml',
        "views/vehicle_details_view.xml",
        "views/vehicle_classification.xml",
        "views/driver_details_and_performance.xml",
        "wizard/vehicle_renewal_wizard_view.xml",
        "wizard/vehicle_number_wizard.xml",
        "wizard/report_wizard.xml",
        "views/servicing_management_view.xml",
        "data/servicing_data.xml",
        "views/fuel_consumption_view.xml",
        "views/due_details.xml",
        "data/fuel_data.xml",
        "views/maintenance_management_view.xml",
        "data/document_data.xml",
        "report/vehicle_number.xml",
        "report/vehicle_movement.xml",
        "views/vehicle_views.xml",
        "report/fuel_consumption_report_template.xml",
        "wizard/report_wizard.xml",
        "views/email_template.xml",
    ],
    'demo': [
        'demo/demo.xml', 
    ],
    "assets": {
    "web.assets_backend": [
        "vehicle_management/static/src/js/custom_button.js",
        "vehicle_management/static/src/xml/button.xml",
        'vehicle_management/static/src/css/custom_wizard.css',
        ]
    },
}