# -*- coding: utf-8 -*-
{
    "name": "Transport Management",
    "author": "Robin Gurung and Asim Ghimire",
    "version": "17.0",
    "category": "",
    "application": True,
    'depends': ['base','vehicle_management',"agriculture_market_place",'account','board'],
    'data': [
        'security/ir.model.access.csv',
        'views/views.xml',
        'views/templates.xml',
        'views/transport_order_views.xml',
        'views/transport_assignment_views.xml',
        'views/transport_pod_views.xml',
        'views/transport_billing_rule_views.xml',
        'views/transport_expense_views.xml',
        'views/transport_manifest_views.xml',
        'views/transport_manifest_line_views.xml',
        'views/customer.xml',
        'wizard/search_wizard.xml',
        'wizard/report_wizard.xml',
        'wizard/expiry_dates_wizard.xml',
        'wizard/invoice_wizard.xml',
        'reports/expiry_dates_template.xml',
        'wizard/service_execution_wizard.xml',
        'reports/service_execution_report_template.xml',
        'wizard/income_expense_report_wizard.xml',
        'reports/income_expense_report_template.xml',
        'wizard/fuel_consumption_report_wizard_view.xml',
        'reports/fuel_consumption_report_template.xml',
        'wizard/driver_staff_expense.xml',
        'reports/invoice.xml',
        'reports/trip_sheet.xml',
        'reports/driver_expense_summary_report.xml',
        'wizard/cargo_tracking_report_wizard.xml',
        'reports/cargo_tracking_report.xml',
        'reports/daily_dispatch_report.xml',
        'reports/delivery_performance.xml',
        'reports/shipment_history_report.xml',
        'wizard/vehicle_utilization_report_wizard.xml',
        'reports/vehicle_utilization_report_template.xml',
        'views/cargo_tracking_view.xml',
        'reports/test_invoice.xml',
        'wizard/cancel_wizard.xml',
        
        
    ],
    'demo': [
        'demo/demo.xml',
    ],
    "assets": {
    "web.assets_backend": [
        'transport_management/static/src/js/print_button.js',
        'transport_management/static/src/xml/print_button.xml',
        'transport_management/static/src/components/chart_renderer/chart_renderer.js',
        'transport_management/static/src/components/chart_renderer/pie_chart.js',
        'transport_management/static/src/components/chart_renderer/chart_renderer.xml',
        'transport_management/static/src/components/kpi_card/kpi_card.js',
        'transport_management/static/src/components/kpi_card/kpi_card.xml',
        'transport_management/static/src/components/transport_dashboard.js',
        'transport_management/static/src/components/transport_dashboard.xml',
        'transport_management/static/src/css/custom.css',
        ]
    },
}

