{
    'name': 'Lekha+',
    'version': '17.0.1.0.4',
    'category': 'Accounting',
    'summary': """Odoo 17 Accounting, Odoo 17 Accounting Reports, Odoo17 Accounting, Odoo Accounting, Odoo17 Financial Reports, Odoo17 Asset, Odoo17 Profit and Loss, PDC, Followups, Odoo17, Accounting, Odoo Apps, Reports""",
    'description': """ Odoo 17 Accounting, The module used to manage the Full
     Account Features that can manage the Account Reports,Journals Asset and 
     Budget Management, Accounting Reports, PDC, Lock dates, Credit Limit, 
     Follow Ups,  Day-Bank-Cash book report, odoo17, odoo17 accounting,
      odoo accounting, v17 accounting,Odoo 17 Accounting, odoo apps""",
    'author': 'Shangrila Informatics',
    'sequence':'2',
    'company': '',
    'depends': ['account', 'sale','bi_so_product_quantity_limit','stock','website','hr_payroll_account_community','hr_payroll_community','web',
                'base_account_budget', 'analytic','izi_dashboard','izi_data','nepal_localization','intercompany_transaction_ept','account_check_printing','mail','base','website_sale'],
    'data': [
        'security/security.xml',
        'security/ecommerce/multi_tenant_groups.xml',
        'security/ir.model.access.csv',
        'security/ecommerce/ir.model.access.csv',
        'data/account_financial_report_data.xml',
        'data/cash_flow_data.xml',
        'data/followup_levels.xml',
        'data/multiple_invoice_data.xml',
        'data/recurring_entry_cron.xml',
        'data/account_pdc_data.xml',
        'data/province_seeder.xml',
        'data/district_seeder.xml',
        'data/palika_seeder.xml',
        'data/business_type_seeder.xml',
        'data/coa_seeder.xml',
        'data/translation.xml',
        'data/payment_data.xml',
        'data/individual_fields.xml',
        'data/organizational_fields.xml',
        # 'data/account_journal_seeder.xml',
        'views/reports_config_view.xml',
        'views/accounting_menu.xml',
        'views/account_group.xml',
        'views/credit_limit_view.xml', 
        'views/account_configuration.xml',
        'views/inherit_date.xml',
        'views/res_config_view.xml',
        'views/website_template.xml',
        'views/login_page_template.xml',
        'views/account_followup.xml',
        'views/followup_report.xml',
        'views/email_template.xml',
        'wizard/asset_depreciation_confirmation_wizard_views.xml',
        'wizard/asset_modify_views.xml',
        'views/account_asset_views.xml',
        'views/account_move_views.xml',
        'views/product_request_views.xml',
        'views/product_template_views.xml',
        'views/company_category_inherit_views.xml',
        'views/multiple_invoice_layout_view.xml',
        'views/multiple_invoice_form.xml',
        'views/account_coa_views.xml',
        'views/master_views.xml',
        'views/location_model.xml',
        'views/business_type_pricing_views.xml',
        'views/stock_picking_form_inherit.xml',
        'views/product_custom_details.xml',
        'wizard/financial_report.xml',
        'wizard/general_ledger.xml',
        'wizard/partner_ledger.xml',
        'wizard/tax_report.xml',
        'wizard/trial_balance.xml',
        'wizard/aged_partner.xml',
        'wizard/journal_audit.xml',
        'wizard/cash_flow_report.xml',
        'wizard/account_bank_book_wizard_view.xml',
        'wizard/account_cash_book_wizard_view.xml',
        'wizard/account_day_book_wizard_view.xml',
        'report/report_financial.xml',
        'report/general_ledger_report.xml',
        'report/report_journal_audit.xml',
        'report/report_aged_partner.xml',
        'report/report_trial_balance.xml',
        'report/report_tax.xml',
        'report/report_partner_ledger.xml',
        'report/cash_flow_report.xml',
        'report/account_bank_book_view.xml',
        'report/account_cash_book_view.xml',
        'report/account_day_book_view.xml',
        'report/account_asset_report_views.xml',
        'report/report.xml',
        'report/multiple_invoice_layouts.xml',
        'report/multiple_invoice_report.xml',
        'views/recurring_payments_view.xml',
        'wizard/account_lock_date.xml',
        'views/account_payment_view.xml',
        'views/res_company_inherit.xml',
        'views/account_ledgers.xml',
        'views/custom_payment.xml',
        'views/account_move.xml',
        'views/payment_template.xml',
        # 'views/portal_bills_payment.xml',
        'views/translation.xml',
        'views/user_views.xml',
        'views/vendor_details.xml',
        'data/ecommerce/cp_attributes.xml',
        'data/ecommerce/ecommerce_sequence.xml',
        'data/ecommerce/settings.xml',
        'views/ecommerce/products_template.xml',
        'views/ecommerce/product_view.xml',
        'views/ecommerce/my_cart.xml',

        'views/ecommerce/checkout.xml',
        'views/ecommerce/payment.xml',
        'views/ecommerce/templates.xml',
        'views/ecommerce/my_wishlist.xml',
        'views/ecommerce/backend/menu.xml',
        'views/notification_views.xml',
        'email_templates/ecommerce/order_placed.xml',
        'email_templates/ecommerce/order_confirmed.xml',
        'views/ecommerce/backend/cp_attributes.xml',
        'views/ecommerce/backend/templates.xml',
    ],
     
    'assets':{
        
        'base_accounting_kit.ecommerce_assets':{
            'base_accounting_kit/static/src/css/ecommerce/style.scss',
           'base_accounting_kit/static/src/css/ecommerce/slick.scss',
           'base_accounting_kit/static/src/css/ecommerce/slick-theme.scss',
           'base_accounting_kit/static/src/css/ecommerce/image-magnifier.scss',
           'base_accounting_kit/static/src/css/ecommerce/style.min.scss',
        },
        'base_accounting_kit.dashboard_assets':{
            'base_accounting_kit/static/src/css/ecommerce/responsive.scss',
        },
        'web.assets_frontend': [
            "base_accounting_kit/static/src/js/lekha_logo.js",
            "base_accounting_kit/static/src/css/global.css",
            "base_accounting_kit/static/src/js/global.js",
            # "base_accounting_kit/static/src/js/ecommerce/*",
            "base_accounting_kit/static/src/js/ecommerce/sidebar.js",
         
            "base_accounting_kit/static/src/js/ecommerce/products.js",
            "base_accounting_kit/static/src/js/ecommerce/product.js",
            "base_accounting_kit/static/src/js/ecommerce/address_config.js",
            "base_accounting_kit/static/src/js/ecommerce/checkout.js",
            "base_accounting_kit/static/src/js/ecommerce/payments.js",
            "base_accounting_kit/static/src/js/ecommerce/index.js",
            "base_accounting_kit/static/src/js/ecommerce/utils/ecommerceUtils.js",
            "base_accounting_kit/static/src/js/ecommerce/utils/success_notification/success.js",
            "base_accounting_kit/static/src/js/ecommerce/utils/success_notification/success.xml",
            'base_accounting_kit/static/src/css/ecommerce/all.scss',
            "base_accounting_kit/static/src/js/ecommerce/my_wishlist.js",
            # "base_accounting_kit/static/src/js/ecommerce/utils/image_viewer.js",
            
        ],
        'web.assets_backend': [
            "base_accounting_kit/static/src/xml/switch_company_selector.xml",
            "base_accounting_kit/static/src/js/switch_company_selector.js",
            "base_accounting_kit/static/src/scss/account_move.scss",
            "base_accounting_kit/static/src/components/*",
            'base_accounting_kit/static/src/css/custom_style.css',
            'views/res_company_detail.xml',
            "base_accounting_kit/static/src/js/backend_global.js",
            'base_accounting_kit/static/src/css/ecommerce/all.scss',
            
        ],
    },
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}

